### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'jsonSubIr'

### ISSUE THREAD

**Issue by jeylites** [NightRang3r/Broadlink-e-control-db-dump#10]
Any idea what the error code is? I have all three files in the same folder with the script....

**User:~ User$  python --version
Python 2.7.10
User:~ User$** 

Last login: Wed Sep  6 01:39:46 on console
User:~ User$ python /Users/User/Desktop/untitled\ folder/getBroadlinkSharedData.py 
Traceback (most recent call last):
  File "/Users/Desktop/untitled folder/getBroadlinkSharedData.py", line 27, in <module>
    jsonSubIr = open("jsonSubIr").read()
IOError: [Errno 2] No such file or directory: 'jsonSubIr'
User:~ User$

**Comment by NightRang3r** [comment]
It can't access one of the files for some reason, not sure why, make sure files are complete and contain data, try to move the files and the script to another folder
