### ISSUE TITLE
my rmpro can't work!

### ISSUE THREAD

**Issue by wojoco** [NightRang3r/Broadlink-e-control-db-dump#13]
I has succeeded got TC2 RF txt,but it work not on my rmpro!  I don't know : 'If not working keep going 3,4,5,6 time until it works with the script'   !  it Meaning:retry?    or new broadlink e-Control Android application "SharedData" json files changed?

**Comment by NightRang3r** [comment]
@wojoco First of all it’s not an issue with the script and this is not a support forum for broadlink products.

If it’s not working you need to duplicate the code not keep sending it

So if your code is 1234 then try 12341234 if that not work try 3 times 123412341234 and so on until it works.

This is already was described in the readme file

**Comment by wojoco** [comment]
@NightRang3r  thanks! It work now!

**Comment by fotanski** [comment]
take care of the conding issues next time,u would get them done well
