### ISSUE TITLE
can't dump

### ISSUE THREAD

**Issue by hsie** [NightRang3r/Broadlink-e-control-db-dump#14]
after I choose the id to proceed on the dumping, the error below appears, would appreciate it if you can help to figure out, thanks in advance

+++++++++++++++++++++++++
Traceback (most recent call last):
  File "getBroadlinkSharedData.py", line 65, in <module>
    jsonIrCodeData = json.loads(jsonIrCode)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting ',' delimiter or ']': line 1 column 95017 (char 95016)

**Comment by NightRang3r** [comment]
Can you provide me the files so I can use it to debug the issue?

**Comment by hsie** [comment]
thanks and pls. find the document you required


[temp.zip](https://github.com/NightRang3r/Broadlink-e-control-db-dump/files/1404108/temp.zip)

**Comment by NightRang3r** [comment]
@hsie 

Your jsonIrCode file looks different than mine, did you get it from the e-Control app , is it the latest version of the app ?

It looks like it is missing }] in the end of the file even if you add it it is still not in the right format, i will continue to investigate it

**Comment by NightRang3r** [comment]
@hsie  Ok figured it out, your "jsonIrCode" file is incomplete and is not a valid json format 
you should add `]}] `to the end of the file 

Your file:

![screen shot 2017-10-21 at 8 11 29 pm](https://user-images.githubusercontent.com/1768915/31854068-327fbafc-b69c-11e7-8630-0ce2cd4063c5.png)

Fix should look like this:

![screen shot 2017-10-21 at 8 11 51 pm](https://user-images.githubusercontent.com/1768915/31854069-37afd23c-b69c-11e7-8d8d-bd830fc4c80a.png)

You can use [https://jsonlint.com/ ](https://jsonlint.com/ )to verify if the file is in the correct format.
