### ISSUE TITLE
error when running getBroadlinkSharedData.py

### ISSUE THREAD

**Issue by sbeagle25** [NightRang3r/Broadlink-e-control-db-dump#15]
Hi, 
I'm new to linux system. 
When I run getBroadlinkSharedData.py, it shows the error below and I don't known how to fix it.

  File "getBroadlinkSharedData.py", line 43
    print "ID:", jsonSubIrData[i]['id'], "| Name:", jsonSubIrData[i]['name']
              ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by NightRang3r** [comment]
You need to use python 2.7

**Comment by sbeagle25** [comment]
New error comes after I run with python 2.7:

Traceback (most recent call last):
  File "getBroadlinkSharedData.py", line 24, in <module>
    import simplejson as json
ImportError: No module named simplejson

**Comment by NightRang3r** [comment]
Please follow the instructions next time, you should install the simplejson library using pip as described in the README file.

**Comment by sbeagle25** [comment]
Requirement already satisfied: simplejson in /usr/local/lib/python3.5/dist-packages
How can I install simplejson for python2.7?
Thanks!

**Comment by NightRang3r** [comment]
1. Try google search first
2. See the readme
3. pip install simplejson

Or

Make sure you execute python 2.7 and not 3

python -m pip install simplejson
