### ISSUE TITLE
getBroadlinkSharedData.py - JSONDecodeError

### ISSUE THREAD

**Issue by AntonLevi** [NightRang3r/Broadlink-e-control-db-dump#22]
hi. 
i use getBroadlinkSharedData.py
i have same error

root@pi:/home/code# python code.py
ID: 1 | Name: button1
ID: 2 | Name: livo
ID: 11 | Name: button2
ID: 15 | Name: Temp
ID: 16 | Name: 10
Select accessory ID: 1
[+] You selected:  button1
Traceback (most recent call last):
  File "code.py", line 58, in <module>
    jsonIrCodeData = json.loads(jsonIrCode)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting ',' delimiter or ']': line 1 column 11066 (char 11065)

have any thoughts what is it?
error in the script code?
I need to install something else?

**Comment by NightRang3r** [comment]
@AntonLevi 
Something is probably wrong with the json files

use https://jsonlint.com/ and paste the each file content to check if it is in a valid json format

**Comment by AntonLevi** [comment]
Yes! thank you. found an error in one of the files. added a sign "]". everything worked out
