### ISSUE TITLE
Unable to locate the installed simplejson, ask for help

### ISSUE THREAD

**Issue by Guoer-xz** [NightRang3r/Broadlink-e-control-db-dump#3]
I use a Mac computer, in accordance with the data to run getBroadlinkSharedData.py, can not find the already installed simplejson, the terminal display as follows:
————————————————————————————————————————
GuoerdeMacBook-Pro:code guoer$ pip3 install simplejson
Requirement already satisfied: simplejson in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages
GuoerdeMacBook-Pro:code guoer$ python getBroadlinkSharedData.py
Traceback (most recent call last):
  File "getBroadlinkSharedData.py", line 20, in <module>
    import simplejson as json
ImportError: No module named simplejson
GuoerdeMacBook-Pro:code guoer$ 
————————————————————————————————————————

**Comment by NightRang3r** [comment]
@Guoer-xz It's not python 3, Use python 2.7
